### ISSUE TITLE
any solution on vmware to virtualbox?

### ISSUE THREAD

**Issue by FalconLK** [Adobee/ACS#4]
I'd love to run the ACS with virtual machine.

However since I don't have the license for the vmware,  do you also have the virtualbox image? or anyway to convert the image without vmware? 

Thank you in advance :)

**Comment by xiongyingfei** [comment]
Hi, there is a version of vmware that is free for personal use: https://www.vmware.com/products/workstation-player.html

**Comment by FalconLK** [comment]
Unfortunately, I'm using mac which means I can't use the Workstation Player. Could you please recommend me another way to run ACS?

**Comment by xiongyingfei** [comment]
Hmm...that is indeed a problem. I cannot figure out an easy way to run it over mac. Also, since all students in this project have graduated, we lack the human power to create another virtual machine image.

If you need the results of ACS on Defejects4J, you may check our ICSE17 paper. Running ACS for new subjects is not possible for now. ACS requires to crawl Github, and recently Github disallowed crawling. 

If you would like to create a program repair tool based on our code, I would recommend our newest tool SimFix: https://github.com/xgdsmileboy/SimFix
This tool has much lighter requirement than ACS, only requiring the code in the same project rather than the whole Github repository. Also, the code is easier to reuse.
